/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testegui;

/**
 *
 * @author LABORATORIO_INFO
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFMenuPrincipal
     */
    public JFMenuPrincipal() {
        initComponents();
        
        btnRotulos.setEnabled(false);
        btnImpressoes.setEnabled(false);
        btnCaixa.setEnabled(false);
        btnFornecedor.setEnabled(false);
        btnUsuarios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvoltar = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        lblMenu = new javax.swing.JLabel();
        painelMainMenu = new javax.swing.JPanel();
        btnEmpregados = new javax.swing.JButton();
        btnFornecedor = new javax.swing.JButton();
        btnCaixa = new javax.swing.JButton();
        btnRotulos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btngerenprodutos = new javax.swing.JButton();
        btnImpressoes = new javax.swing.JButton();
        btnvoltar1 = new javax.swing.JToggleButton();

        btnvoltar.setText("Voltar");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste GUI - Menu");
        setResizable(false);
        setSize(new java.awt.Dimension(570, 410));

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");
        lblMenu.setToolTipText("");

        painelMainMenu.setBackground(new java.awt.Color(215, 220, 224));
        painelMainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnEmpregados.setMnemonic('e');
        btnEmpregados.setText("Empregados");
        btnEmpregados.setPreferredSize(new java.awt.Dimension(100, 100));
        btnEmpregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpregadosActionPerformed(evt);
            }
        });

        btnFornecedor.setMnemonic('f');
        btnFornecedor.setText("Fornecedor");
        btnFornecedor.setToolTipText("");
        btnFornecedor.setPreferredSize(new java.awt.Dimension(100, 100));
        btnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorActionPerformed(evt);
            }
        });

        btnCaixa.setMnemonic('c');
        btnCaixa.setText("Caixa");
        btnCaixa.setToolTipText("");
        btnCaixa.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixaActionPerformed(evt);
            }
        });

        btnRotulos.setMnemonic('r');
        btnRotulos.setText("Rótulos");
        btnRotulos.setPreferredSize(new java.awt.Dimension(100, 100));
        btnRotulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotulosActionPerformed(evt);
            }
        });

        btnUsuarios.setMnemonic('u');
        btnUsuarios.setText("Usuários");
        btnUsuarios.setToolTipText("");
        btnUsuarios.setPreferredSize(new java.awt.Dimension(100, 100));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btngerenprodutos.setMnemonic('u');
        btngerenprodutos.setText("Gerenciar Produtos");
        btngerenprodutos.setToolTipText("");
        btngerenprodutos.setPreferredSize(new java.awt.Dimension(100, 100));
        btngerenprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngerenprodutosActionPerformed(evt);
            }
        });

        btnImpressoes.setMnemonic('i');
        btnImpressoes.setText("Impressões");
        btnImpressoes.setPreferredSize(new java.awt.Dimension(100, 100));
        btnImpressoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpressoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelMainMenuLayout = new javax.swing.GroupLayout(painelMainMenu);
        painelMainMenu.setLayout(painelMainMenuLayout);
        painelMainMenuLayout.setHorizontalGroup(
            painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmpregados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRotulos, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(btnImpressoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngerenprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelMainMenuLayout.setVerticalGroup(
            painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmpregados, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btngerenprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRotulos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(painelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImpressoes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btnFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        btnvoltar1.setBackground(new java.awt.Color(255, 204, 204));
        btnvoltar1.setText("Encerrar Seção");
        btnvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(painelMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 218, Short.MAX_VALUE)
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvoltar1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(12, 12, 12)
                .addComponent(painelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnvoltar1)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaixaActionPerformed

    private void btnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFornecedorActionPerformed

    private void btngerenprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngerenprodutosActionPerformed
        // TODO add your handling code here:
        JFGerenciarProdutos abrir = new JFGerenciarProdutos();
            abrir.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btngerenprodutosActionPerformed

    private void btnImpressoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpressoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImpressoesActionPerformed
        
    private void btnEmpregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpregadosActionPerformed
        JFGerenciarFuncionarios abrir = new JFGerenciarFuncionarios();
            abrir.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnEmpregadosActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar1ActionPerformed
        JFLogin abrir = new JFLogin();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnvoltar1ActionPerformed

    private void btnRotulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotulosActionPerformed
        
    }//GEN-LAST:event_btnRotulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa;
    private javax.swing.JButton btnEmpregados;
    private javax.swing.JButton btnFornecedor;
    private javax.swing.JButton btnImpressoes;
    private javax.swing.JButton btnRotulos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btngerenprodutos;
    private javax.swing.JToggleButton btnvoltar;
    private javax.swing.JToggleButton btnvoltar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel painelMainMenu;
    // End of variables declaration//GEN-END:variables

    private void setEnable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
